language: python
python:
- 3.6
- 3.5
- 3.4

install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: s-weigand
  server: https://test.pypi.org/legacy/
  password:
    secure: b0mx1bXto2DubK6wQ6p21wxhCAa0mnxp3nv87of4rblAltP+5yHdkcVrENjXeTPZ8guc6jVpVkgL/bIYD3TFV3QfFa42gv1EJQ8pB5GJ6HRLsZrYx/PGgP0vpBsj6Wa6MKQHnyyr8QmKViNDzIr1jKHdLISLSe3ifMLWRxukFffb/e6vWWU4FWUGLpMwdlpAwclPuaUDxYqh45TEa0y/3RzQZ8aCB5gffj0T3/8sMkQW4GdgOI6gZ/KYVhnuP9aB1VbT249KJ0PxwN/U/K21cvYh1Vjiv61qhtmXZQ3NNNoEZD/dJqEYJepaGX3BhRqn648p2j+THZJUKO9RHlKNJ/pG3fImicRz9cwPXNZEahafQJ2cCpc+KNY86ktcB0hW3YMtMLzSrvlO/5rBWAueZcFxxLjKQi1Tz2UjRdsHG5z3XUOzpvnP8fgfPORCuE53TBA4+dJeqoh3G8HBrJMzPUv9znWoHujZRXRn0RHssaRtUSmZ9mmQr/2MW7cq0Kutdro8/Eiporshb1/qLS6gn40xkPlQe1BFTrGdKngGboirpHxxIdI6UU4pR6QHWnfjprClb+kC3kActMXYyuWRZWVHOmHLjSLqrDCHiONzmmw1YCUYNejy+SfQo7o0wH7WjglVDBOEgpUbbl2txC0JesPCgozlEXxP7zk3w/TvgoU=
  on:
    tags: true
    repo: s-weigand/python-packaging-test
    python: 3.6
