language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      before_install:
        - echo "before_install"
        - python -m pip install -U pip>=9.0.1
        - pip install tox
      script:
        - tox
      after_success:
        # this prevents the tests to upload stuff to coveralls.io
        - echo "done"

    # LINUX
    - python: "3.6"
      name: linux-py36

    - python: "3.7-dev" # 3.7 development branch
      name: linux-py37

    # OSX
    - language: generic
      python: 3.6
      os: osx
      name: osx-py36
      before_install:
        - echo "before_install"
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
        - source activate py36

    - language: generic
      python: 3.7
      name: osx-py37
      os: osx
      before_install:
        - echo "before_install"
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py37 python=3.7 -y
        - source activate py37

install:
  - pip install coveralls
  - python -m pip install -r requirements_dev.txt

script:
  - pip install .
  - py.test  tests
  - pip freeze

deploy:
  # full deploy
  - provider: pypi
    distributions: sdist bdist_wheel
    user: s-weigand
    server: https://test.pypi.org/legacy/
    skip_cleanup: true
    password:
      secure: votHCGQUaFfMqTha9GkNLoB3oWlB3CA5VNtiFSKJUxIJAUj7wVCtKct9pl1XlNZ9R0IJ/XQARf0vIewP24GgzkYBHKDPXegLLm12RaL+c9qP9qsKOM/EsJbwdu1yo/BM9zaX8HoQ0XjCQPw/G1UCTLU04rlOFheAkpReOQhApiUD3pJop2bSO9PctWOajAdoCbeG4qP/wrcNNx4aj+CLLeNkPFlb9et9NDSBV8JlZnXA8wPugru3oBkgG7D6K45pVwXiNYMhvXAJc166p5OHGMazVzt0KZAl1V7bISdQwsRUF5daNHX7K6oO5vS82CaIYv4joyYMBIXo4PDmP9RweaM+2mF1Lms8KvR/UbKG6g7IhuQkcfMR0lqPmpdEBOOCuY4TqFeQ/DUEGVjefmwQ7X2UDlFG+MRZK932l9Q8Ma74/CtGAbHNvl0ejWhR7IUbhtcxduQ1SV+l9ZQBSqLD8kIGoGft9rtvh5K0zfOR7rIbxbzSmiCiGfcsbEqb+K7IZCN6X5NxSdMUelmgvospjMNYVv8S3fQNWOBY0yyoAOCpJp9VDrJCLjmrNfzkm6GIBFjAyPdSxNAk3YbXo8OsYgoMoUzcHFfXKiv9/RYo+4TZT27geqg8hIgnZycHjjZPts7kCmRFGPOvx511PIWyMa93em4OWfx99IbGqoSZJag=
    on:
      tags: true
      repo: s-weigand/python-packaging-test
      condition: "$DEPLOY_ALL = true"
